In [2]:
#image representation
import cv2
import numpy as np
import random

In [16]:
img=cv2.imread('cat.jpg',1)
print(img.shape)

(383, 510, 3)


In [31]:
#Accessing pixel values
print(img[300][0:5])

[[ 62  59 238]
 [ 55  50 231]
 [ 52  44 228]
 [ 56  42 230]
 [ 54  37 225]]


In [38]:
#changning pixel color
for i in range(100):
    for j in range(img.shape[1]):
        img[i][j]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [153]:
#copy and past parts of the image
img=cv2.imread('cat.jpg',1)
tag=img[0:200,150:350] #peace
img[0:200,310:510]=tag #position
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
#draw line
img=cv2.imread('cat.jpg',1)
cv2.line(img,(0,0),(510,510),(0,255,255),10)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
Img=np.zeros((512,512,3),dtype='uint8')
cv2.line(Img,(0,0),(512,512),(0,255,255),10)
cv2.line(Img,(512,512),(0,0),(255,250,255),10)
cv.rectangle(img,(384,0),(510,128),(0,255,0),3)
cv2.imshow('image',Img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [56]:
Img=np.zeros((512,512,3),dtype='uint8')
cv2.line(Img,(0,0),(512,50),(0,255,255),10)
cv2.line(Img,(0,512),(0,0),(255,255,0),10)
cv2.imshow('image',Img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
img=np.zeros((512,512,3),np.uint8)
# draw line
cv2.line(img,(0,0),(512,512),(255,250,255),10)
cv2.line(img,(512,0),(0,512),(255,0,255),10)
#draw rectangle
cv2.rectangle(img,(384,0),(510,128),(0,255,255),10)
cv2.rectangle(img,(0,128),(128,0),(0,0,255),10)
cv2.rectangle(img,(384,383),(510,510),(255,0,0),10)
cv2.rectangle(img,(0,384),(128,510),(255,255,0),10)
#draw circle
cv2.circle(img,(256,256),70,(0,255,0),10)
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()